name: Interoperability Tests

on:
  - push
  - pull_request

jobs:
  interop-tests:
    name: Interoperability Tests

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24.1.1"
          elixir-version: "1.13.3"

      - name: Set up cache
        uses: actions/cache@v3.0.2
        id: cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: interop-tests-${{ runner.os }}-${{ matrix.otp-version }}-${{ matrix.elixir-version }}-${{ hashFiles('mix.lock') }}

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        working-directory: ./interop
        run: mix deps.get

      - name: Run interop tests
        working-directory: ./interop
        run: mix run script/run.exs
