name: Styles

on:
  - push
  - pull_request


jobs:
  styles:
    name: Check styles

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24.1.1"
          elixir-version: "1.13.3"

      - name: Set up cache
        uses: actions/cache@v3.0.2
        id: cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: styles-${{ runner.os }}-${{ matrix.otp-version }}-${{ matrix.elixir-version }}-${{ hashFiles('mix.lock') }}

      - name: Install dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Check format
        run: mix format --check-formatted
